### ISSUE TITLE
Crash when Compressing to File Named as Existing File

### ISSUE THREAD

**Issue by thewizardstudio** [veniosg/Dir#104]
#### Expected Behavior
Compressing a file using the same name as a file already existing in the directory overwrites existing file after confirmation.

#### Actual Behavior
Compressing a file using the same name as a file already existing in the directory causes a Crash.

#### How to Reproduce
1. Launch Dir 1.5.2.3 on Android 8.1.0
2. Navigate to a Directory with a File in it
3. Select and Hold the File to Select
4. Select the Operations button in Upper Right
5. Select Compress
6. Enter any Name
7. Select OK
8. Repeat Steps 3 through 5
9. Enter the same Name as used in Step 6
10. Select OK
11. Select Yes

---
Device: Pixel 2 XL
OS: Android 8.1.0
App Version: 1.5.2.3
---

#### Recording of the Bug
![CrashCompressSame.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516820620/jtut2qh55imxqnyk0ybt.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/crash-when-compressing-to-file-named-as-existing-file">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by veniosg** [comment]
Thanks for the detailed reports!

**Comment by thewizardstudio** [comment]
@veniosg My pleasure!  Let me know if you'd like any focused testing in the future.
