### ISSUE TITLE
Can't install APK

### ISSUE THREAD

**Issue by lcrocker** [veniosg/Dir#108]
Amazon Fire HD 8 (6th Generation) tablet.
Fire OS 5.6.0.1 (Lollipop-based)
"Allow external program sources" is checked in security settings.

Navigate to  "Downloads", select a .apk file, get "no matching program" dialog. 

Works correctly on my Samsung Galaxy Tab S2 running Android 7.0, so might just be an Amazon thing.

**Comment by veniosg** [comment]
I have heard this before, on a N5X if I recall correctly, but was sadly unable to reproduce. 
How do other file managers handle it? 
Is there an Amazon equivalent to AOSP's Downloads app? What happens if you select the apk from there?

**Comment by lcrocker** [comment]
If I can figure out how to sideload the Downloads app, I'll try it and let you know.

On January 30, 2018, at 4:43 AM, George Venios <notifications@github.com> wrote:

I have heard this before, on a N5X if I recall correctly, but was sadly unable to reproduce.
How do other file managers handle it?
Is there an Amazon equivalent to AOSP's Downloads app? What happens if you select the apk from there?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/veniosg/Dir","title":"veniosg/Dir","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/veniosg/Dir">https://github.com/veniosg/Dir</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@veniosg in #108: I have heard this before, on a N5X if I recall correctly, but was sadly unable to reproduce. \r\nHow do other file managers handle it? \r\nIs there an Amazon equivalent to AOSP's Downloads app? What happens if you select the apk from there?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/veniosg/Dir/issues/108#issuecomment-361582236">https://github.com/veniosg/Dir/issues/108#issuecomment-361582236</a>"}}}

**Comment by veniosg** [comment]
This should be fixed in 1.5.6 (just released on Play, give it some time to fully roll out).
Thanks for the help in identifying the problem :)
