### ISSUE TITLE
No delete option

### ISSUE THREAD

**Issue by lcrocker** [veniosg/Dir#109]
Amazon Fire HD 8 (6th Generation) tablet.
Fire OS 5.6.0.1 (Lollipop-based)

Navigate to  "Downloads", select any file, touch three-dot menu. Menu options are "Create shortcut", "Bookmark", "Details", and "Select all". No "Delete". Can't find any other way to delete a file.

This also happens on my Samsung Galaxy Tab S2 running Android 7.0, so it appears to not be just an Amazon thing.

**Comment by veniosg** [comment]
I know this is hidden and I'm planning a redesign to remedy it. In the meantime: 
Long press any files you want deleted, press the "File and pencil" icon, and then select "Delete".
