### ISSUE TITLE
want to create a logo representing your project in the future

### ISSUE THREAD

**Issue by damahsyari** [veniosg/Dir#118]
Hello @George Venios ,
I'm a graphic designer and i want your permission to design a logo and an icon for your application.
Best regards.

**Comment by veniosg** [comment]
I'm afraid we don't need a new icon. I'm perfectly happy with the current one and it has only been updated a week or so ago. Thanks for offering your help.

**Comment by damahsyari** [comment]
thanks sir .. but may I contribute to your project on the logo. you do not
have to use it sir just as my contribution to the experience in the
opensource world

Pada tanggal Sab, 24 Mar 2018 19.41, George Venios <notifications@github.com>
menulis:

**Comment by damahsyari** [comment]
do you allow me to contribute sir?

Pada tanggal Sab, 24 Mar 2018 19.49, Damah Syari <damahtaurus@gmail.com>
menulis:

**Comment by damahsyari** [comment]
thanks sir .. but may I contribute to your project on the logo.you do not have to use it sir just as my contribution to the experience in the opensource world

**Comment by damahsyari** [comment]
may i make a logo for your app sir?
