### ISSUE TITLE
What's your plan for Android Q?

### ISSUE THREAD

**Issue by staltz** [veniosg/Dir#128]
Hello fellow FOSS developer, I build the [Manyverse](https://github.com/staltz/manyverse) app which is also on F-Droid.

Have you heard of Google's schedule to deprecate shared external directories? [See this article](https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/).

Your app uses `Environment.getExternalStorageDirectory()` which Google is [deprecating in API level 29](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()).

https://github.com/veniosg/Dir/blob/4c7f2799fadd9663b5ae7b35e8381725325e6610/app/src/main/java/com/veniosg/dir/android/activity/FileManagerActivity.java#L103

I think this is terrible news from Google, and I'd like to use `getExternalStorageDirectory()` too. This change in Android Q will affect all File Managers and significantly change the UX and possible features for users. I would like to know if you have any ideas what could be done.

**Comment by veniosg** [comment]
There are no plans to target that android version so unfortunately I haven't thought of a workaround that might work.
You might want to take a look at the Scoped Directory Access APIs, I'd be surprised if there is no way to replicate the behaviour you need using that.
