### ISSUE TITLE
Using screenshot templates (mockups) for Play Store screenshots

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#44]
Hey George,

I think using templates for screenshots (often called mockups) on Google Play may be a great idea. I have listed some links below, though a simple Google search gives lots of them.

https://appinstitute.com/app-screenshot-maker/

https://davinciapps.com/

http://www.appscreenshot.me/

https://appure.io/

<br>
<br>
Sanmay

**Comment by veniosg** [comment]
Running a Play store experiment to check impact of this type of screenshots. Will either revert or fully roll out based on results in a couple of weeks. Closing this.
