### ISSUE TITLE
Using a material styled background for navigation drawer

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#45]
Hey George,

I tried the app, and it's awesome. I was wondering if it may be better to use a background rather than the cyan-blue color, in the navigation drawer. We may see any Google made app for an example, say Google Plus.

I understand that it might play a role in increasing app size for no reason, but still I thought to let you know. Even if there may be a case where we used colorful pattern rather than cyan-blue, it might look better

A simple Google image search for `material styled wallpapers` may give satisfactory results.

<br>
<br>
Sanmay

**Comment by veniosg** [comment]
This is actually a conscious decision. Google Plus rightly uses the user's cover as a background for the user profile info area, but Dir has no such notion and only shows the title of the panel - which in itself is a slight stretch but I felt it makes the layout clearer. That colour is actually the selected theme's accent (you can also see it enabled settings) and is chosen to match the primary colour of each theme. 
I don't see how adding a stock image as the header background can improve the experience, and I believe it detracts from the overall style of the app so I'm going to keep this as is.

**Comment by SanmayJoshi** [comment]
Perfectly cool. :smile:
