### ISSUE TITLE
File/storage analysis screen

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#48]
Hey George,

On opening Dir, we land on Phone Storage. Many other apps show a screen with analysis of different file types(apps, images, videos, music, documents, compressed, encrypted) . I think it certainly helps, as I remember, I used it quite a lot. This way Dir might not as well need the default bookmarks it has. It would be even awesome if Dir showed how much Phone Storage and SD card has filled on this screen.

Thanks.

**Comment by veniosg** [comment]
I wouldn't change the home screen content as it doesn't fit with the rationale behind Dir - namely a no fuss, simple file manager. 

For the specifics of this, what would be the difference between this screen and Android's own "Storage" screen?

**Comment by veniosg** [comment]
Closing until this is more concrete or becomes a popular request.

**Comment by SanmayJoshi** [comment]
Please correct me if I'm wrong.

Storage screen shows info about which file type occupies how much storage. On "Stats" screen of Dir, it may be plausible to show different file types(img,vids,etc..) along with their numbers. Also, tapping on one such type would land user on a screen featuring all files of given file type ordered in a systematic manner. This way, even if files of same file type, different extension are scattered throughout the phone, located in different folders, user would be able to perform operations very easily.

Cheers :)
