### ISSUE TITLE
Ensure launcher icon/shortcuts work after upgrade to 1.5

### ISSUE THREAD

**Issue by veniosg** [veniosg/Dir#72]
Since FileManagerActivity has moved, it is possible that launcher shortcuts are broken. 
Check and fix if necessary.

**Comment by pavlospt** [comment]
@veniosg this seems to be working fine, although I suggest adding an `<activity-alias>` to avoid cases like these in the future!

**Comment by veniosg** [comment]
To confirm, did you install 1.4.6, created a shortcut to a file and dragged
the launcher icon on the home screen, updated to latest master and both
shortcuts still worked?

**Comment by pavlospt** [comment]
Certainly not  😂  Will do tomorrow now that I know the flow :P

**Comment by veniosg** [comment]
Sorry for the unclear description! 😁
