### ISSUE TITLE
Intent.ACTION_SEND support

### ISSUE THREAD

**Issue by veniosg** [veniosg/Dir#76]
Splitting this from #66

**Comment by veniosg** [comment]
@isabsent Please reply here. 
Can you clarify what the functionality this would support is? I'm not sure I get it from the link you sent, it seems like it's about receiving data, would this be used in a "save as" interface?

Fair enough about the pull request, I guess just sending the code would be ok in this instance.

**Comment by isabsent** [comment]
Such feature would be useful if a third party send data as a file or a data stream to your file manager. In our fork of your app we are taking a file or data stream from other apps to put it in our encrypted containers as Google Drvie with his "Send copy" action for example. You can save a data stream as a file I think, but I am not insist on this functionality.

**Comment by isabsent** [comment]
There is [unresolved problem with SD and USB](https://stackoverflow.com/questions/40047883/how-to-differentiate-between-usb-and-sd-mount) and my code looks like a mess when I have tried to make some workaround for it :(

**Comment by veniosg** [comment]
Thanks for the details! This sounds very involved and looking at the roadmap it's too niche a feature to push others out. I will close this for now and we can revisit once we have a more stable architecture (first migration is part of 1.5) and more basic features are in.
