### ISSUE TITLE
Not loading /storage/emulated

### ISSUE THREAD

**Issue by Lonami** [veniosg/Dir#89]
Testing this application from F-Droid, hope the issue wasn't solved yet. Anyway the application starts correctly in `/storage/emulated/0` on my Xperia M4 (Marshmallow, 6.0), but if I go a level up to `/storage/emulated`, then it shows no folder at all. Had a similar issue programming myself, not sure how to solve it. Maybe check the roots available and show items you know from the root path (e.g. from such path you could know you had to show a `0` folder there).

**Comment by veniosg** [comment]
I'm convinced this is because Android read protects that directory. Can you try with a file manager that has root access? I don't have any rooted devices myself :)

**Comment by Lonami** [comment]
Both Ghost Commander and Amaze fail to load `/storage/emulated` without root (oops), and they both work once I give them root.

**Comment by veniosg** [comment]
Thanks for checking! I'll close this then because it's just a side effect of #2
