### ISSUE TITLE
F-Droid version causing a boot loop

### ISSUE THREAD

**Issue by tetris4** [veniosg/Dir#92]
I'm afraid Dir 1.4.6 on F-Droid suffers from this known bug:
https://gitlab.com/fdroid/fdroiddata/issues/979

**Comment by veniosg** [comment]
From that thread it seems that updating to build tools 27 fixes the issue. Is that your experience too? Are you able to reproduce this issue on your devices so we can test if the fix actually works for Dir?

**Comment by tetris4** [comment]
Not a coder, but I've followed this bug for a while and it seems several application devs fixed it by using build tools 27 indeed. And yes, I am the one that reported [the issue with Dir](https://gitlab.com/fdroid/fdroiddata/issues/979#note_53211828) in that thread so when a new f-droid version is out with a fix I would gladly test and report back.

**Comment by veniosg** [comment]
Sounds good, I'll ping you here when the code is out

**Comment by veniosg** [comment]
@tetris4 1.5.2.3 is out on FDroid and uses the latest build tools. Can you please confirm this fixes the issue?

**Comment by veniosg** [comment]
Closing this as the only thing we could do from the app side is done. This is sadly an issue with the ROMs. Still curious to see whether this was fixed so please leave a comment if you try.

**Comment by tetris4** [comment]
Hi, the ROM I use got updated in the meantime with a fix for this, so I can't check for the problem.
I had tested with version 1.5.1 before the update and there was an improvement: no boot loop, but crashes of the system UI. So hopefully 1.5.2.x will have done the trick!
Thanks for your work on this app and keep it up!

**Comment by veniosg** [comment]
No worries, thanks for following up!
