### ISSUE TITLE
android kitkat 4.4.2 support

### ISSUE THREAD

**Issue by lucamp** [veniosg/Dir#93]
Hi,
Could you please consider supporting android kitkat (mine is 4.4.2) and maybe from 4.0 onward

Thanks
Luca

**Comment by veniosg** [comment]
Unfortunately this was a concious decision as the maintenance effort and apk size would both increase considerably if Dir was to support anything below 5.0. Dir versions before 1.2 did in fact support it but the app has changed considerably since then.
